In [1]:
import rispy
import pandas as pd
from pathlib import Path
import os
import sys

In [2]:
# os.chdir("../")
print(f"Current working directory: {os.getcwd()}")

Current working directory: D:\projects\MateReview\notebooks

In [5]:
filepath = Path("../data/REV1-SCOPUS-1/2026-03-26_Export.csv")
df = pd.read_csv(filepath, encoding="utf-8", header=0)
df.head()

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,ISBN,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID
0,Li Z.; Scandolo S.,"Li, Z. (57213002214); Scandolo, S. (35549702800)",57213002214; 35549702800,A physics-informed long-range polarizable pote...,2026,Journal of Chemical Physics,164,4,044107,NaN,...,NaN,JCPSA,41574796.0,English,J Chem Phys,Article,Final,NaN,Scopus,2-s2.0-105028458061
1,Yan J.; Bai L.; Liu H.; Zhang Z.; Tang Y.; Zha...,"Yan, Jiaxing (59154534900); Bai, Lele (5798571...",59154534900; 57985715800; 57113931700; 6038952...,In-Process Tool Wear Prediction Enabled by Phy...,2026,IEEE Transactions on Industrial Informatics,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,English,IEEE Trans. Ind. Inf.,Article,Article in press,NaN,Scopus,2-s2.0-105030043568
2,Lv M.; Gu M.-Y.; Xu X.,"Lv, Min (60145366900); Gu, Meng-Yuan (60479684...",60145366900; 60479684000; 60479343000,Research on accurate prediction method of disp...,2026,Proceedings of SPIE - The International Societ...,14069,NaN,140690D,NaN,...,979-890232097-5,PSISD,NaN,English,Proc SPIE Int Soc Opt Eng,Conference paper,Final,NaN,Scopus,2-s2.0-105032520148
3,Lüthje J.T.; Langiu M.; Mitsos A.,"Lüthje, Jannik T. (57204522119); Langiu, Marco...",57204522119; 57222180477; 8979766700,Working fluid screening for ORC-based Carnot b...,2026,Optimization and Engineering,27,1,NaN,587,...,NaN,NaN,NaN,English,Optim. Eng.,Article,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-105017062962
4,Choi K.; Joe J.; Ha S.; Lee D.; Mun J.,"Choi, Kwangwon (58182397200); Joe, Jaewan (551...",58182397200; 55125736100; 59935088800; 5993520...,A non-intrusive experimental study on the ther...,2026,Energy and Buildings,359,NaN,117257,NaN,...,NaN,ENEBD,NaN,English,Energy Build.,Article,Final,NaN,Scopus,2-s2.0-105032192885

In [6]:
# Turn into dataframe
df.columns

Index(['Authors', 'Author full names', 'Author(s) ID', 'Title', 'Year',
       'Source title', 'Volume', 'Issue', 'Art. No.', 'Page start', 'Page end',
       'Cited by', 'DOI', 'Link', 'Affiliations', 'Authors with affiliations',
       'Abstract', 'Author Keywords', 'Index Keywords',
       'Molecular Sequence Numbers', 'Chemicals/CAS', 'Tradenames',
       'Manufacturers', 'Funding Details', 'Funding Texts', 'References',
       'Correspondence Address', 'Editors', 'Publisher', 'Sponsors',
       'Conference name', 'Conference date', 'Conference location',
       'Conference code', 'ISSN', 'ISBN', 'CODEN', 'PubMed ID',
       'Language of Original Document', 'Abbreviated Source Title',
       'Document Type', 'Publication Stage', 'Open Access', 'Source', 'EID'],
      dtype='str')

In [21]:
# Filter by year > 2021, type is Jurnal and has DOI
filtered_df = df[(df["year"].astype(int) > 2021) & (df["type_of_reference"] == "JOUR") & (df["doi"].notna())]
print(f"Filtered entries: {len(filtered_df)}")
filtered_df.head()

Filtered entries: 3763

,type_of_reference,authors,title,year,secondary_title,volume,number,custom7,doi,urls,...,custom2,language,alternate_title1,type_of_work,name_of_database,notes,secondary_authors,start_page,end_page,short_title
0,JOUR,"[Li, Z., Scandolo, S.]",A physics-informed long-range polarizable pote...,2026,Journal of Chemical Physics,164,4,044107,10.1063/5.0292167,[https://www.scopus.com/inward/record.uri?eid=...,...,41574796,English,J Chem Phys,Article,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,NaN,NaN,NaN,NaN
1,JOUR,"[Yan, J., Bai, L., Liu, H., Zhang, Z., Tang, Y...",In-Process Tool Wear Prediction Enabled by Phy...,2026,IEEE Transactions on Industrial Informatics,NaN,NaN,NaN,10.1109/TII.2026.3658032,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,IEEE Trans. Ind. Inf.,Article,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,NaN,NaN,NaN,NaN
3,JOUR,"[Lüthje, J.T., Langiu, M., Mitsos, A.]",Working fluid screening for ORC-based Carnot b...,2026,Optimization and Engineering,27,1,NaN,10.1007/s11081-025-10026-9,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,Optim. Eng.,Article,Scopus,[Export Date: 24 March 2026; Cited By: 1; Corr...,NaN,587,616,NaN
4,JOUR,"[Choi, K., Joe, J., Ha, S., Lee, D., Mun, J.]",A non-intrusive experimental study on the ther...,2026,Energy and Buildings,359,NaN,117257,10.1016/j.enbuild.2026.117257,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,Energy Build.,Article,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,NaN,NaN,NaN,NaN
5,JOUR,"[Kumar Yadav, A.]",Artificial Intelligence in Accelerating Materi...,2026,ChemistrySelect,11,7,e07191,10.1002/slct.202507191,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,ChemistrySelect,Review,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,NaN,NaN,NaN,NaN

In [9]:
filtered_df = df[(df["year"] > 2021) & (df["type_of_reference"] == "JOUR") & (df["doi"].notna())]

TypeError: '>' not supported between instances of 'str' and 'int'